---
- name: Create Python 3.4 Site
  hosts: vagrant
  remote_user: vagrant

  vars:
    python_version: 3.4
  vars_prompt:
    - name:    domain
      prompt:  Domain Name (e.g. codeup.dev)
      private: no

  pre_tasks:
    - name: Development domains must end with .dev
      assert:
        that: domain.endswith(".dev")

  roles:
    - Python
