---
- name: Lock root User
  command: passwd -l root

- name: Remove Sudo and Admin Group Rights
  lineinfile:
    dest:     /etc/sudoers
    regexp:   "^{{ item }}"
    state:    absent
    validate: "visudo -cf %s"
  with_items:
    - "%sudo"
    - "%admin"
  tags:
    - sudoer

- name: Create Console User Account
  user:
    name:     "{{ console_user }}"
    password: "{{ console_password }}"
    shell:    /bin/bash
    state:    present
    groups:   www-data
    append:   yes

- name: Add Console User to Sudoers
  lineinfile:
    dest:     /etc/sudoers
    line:     "{{ console_user }} ALL=(ALL) ALL"
    state:    present
    validate: "visudo -cf %s"
  tags:
    - sudoer

- name: Allow Some Passwordless Sudo Commands
  lineinfile:
    dest:     /etc/sudoers
    line:     "{{ console_user }} ALL=NOPASSWD: /usr/sbin/service nginx reload"
    state:    present
    validate: "visudo -cf %s"
  tags:
    - sudoer

- name: Keep Rbenv Root When Sudo-ing
  lineinfile:
    dest: /etc/sudoers
    line: Defaults	env_keep += "RBENV_ROOT"
    insertafter: Defaults\s+env_reset
    state: present
    validate: "visudo -cf %s"
  tags:
    - sudoer

- name: Ensure Public Key is in authorized_keys
  authorized_key:
    user: "{{ console_user }}"
    key:  "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Update SSH Parameters
  lineinfile:
    dest:   /etc/ssh/sshd_config
    state:  present
    regexp: "^{{ item.key }}"
    line:   "{{ item.key }} {{ item.value }}"
  with_items:
    - { key: 'Port',                   value: '{{ ssh_port | default("22") }}' }
    - { key: 'PermitRootLogin',        value: 'no' }
    - { key: 'PasswordAuthentication', value: 'no' }
    - { key: 'LoginGraceTime',         value: '20' }
    - { key: 'X11Forwarding',          value: 'no' }
    - { key: 'AllowUsers',             value: '{{ console_user }}' }
  notify: Restart SSH
