---
- name: Change root Password
  user: name=root password={{ new_root_password }}
  when: new_root_password is defined

- name: Lock root User (use 'sudo passwd root' to re-enable)
  command: passwd -l root

- name: Remove sudo Group Rights
  lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent validate='visudo -cf %s'

- name: Create codeup User Account
  user: name={{ new_user }} password={{ new_user_password }} shell=/bin/bash state=present

- name: Add User codeup to Sudoers
  action: lineinfile dest=/etc/sudoers regexp="^{{ new_user }} ALL" line="{{ new_user }} ALL=(ALL) ALL" state=present validate="visudo -cf %s"

- name: Ensure Public Key is in authorized_keys
  authorized_key: user="{{ new_user }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Install Bash Profile
  template: src=bashrc.j2 dest=/home/{{ new_user }}/.bashrc

- name: Update SSH Parameters
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
  with_items:
    - { key: 'Port', value: '{{ ssh_port | default("22") }}' }
    - { key: 'PermitRootLogin', value: 'no' }
    - { key: 'PasswordAuthentication', value: 'no' }
    - { key: 'LoginGraceTime', value: '20' }
    - { key: 'X11Forwarding', value: 'no' }
    - { key: 'AllowUsers', value: '{{ new_user }}' }
  notify:
    - Restart SSH
